src/components/InputText/index.scss
src/components/InputText/index.tsx

Add clear button

---

src/components/LineSelector/index.scss

|Before|After|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/1962469/67673393-986f3380-f982-11e9-90d7-8cb245f59507.png" width="360">|<img src="https://user-images.githubusercontent.com/1962469/67673383-94dbac80-f982-11e9-9710-447f1aa92064.png" width="360">|

fix(ui): blue pill bug on iOS

---

src/customBootstrap.scss

fix(audit): more contrast for primary color

---

src/components/Results/index.scss

fix(safari): badge and show forms

---

package.json

chore(jest): fix transformer warning

---

.travis.yml
package-lock.json
package.json

Fix coveralls

---

src/utils/translator.ts
tests/bcp47.test.ts
tests/translator.test.ts

Fix search speed (create additional cache) + add tests

Fix search speed

---

src/translations/data.json

Poljsky prěvod - jest li vidmy uže?

Poljsky prěvod?

---

src/translations/data.json

Nova prosba za slivanje s razširenymi bulgarskymi prěvodami.

Extend Bulgarian translations

---

src/translations/data.json

tl;dr
"Зважати на" is a correct version.
https://onlinecorrector.com.ua/uk/вважатися-зважати-на/
Thanks to Natasha Pekar for noticing.

translation(ukr): fix preposition wording

---

src/components/InputText/index.tsx

I have a lot of time during the isolation :)
Ja imaju mnogo vrěmena v tečenju izolacije :)
See this issue:
https://github.com/scherebedov/interslavic/issues/71

Implement throttle on search

---

src/legacy/conjugationVerb.ts

Here, I tried to 
1) add some comments explaining the logic
2) split some extremely long functions into several pieces
3) simplify logic in some places where it is obvious (according to my admittedly subjective assessment) that the new version is equivalent.

slight refactor of verb conjugation

---

src/reducers/reducers.ts

fixed formatting on change "Part Of Speech" filter

---

src/translations/data.json

i18n: fix interslavic translation

---

package-lock.json
package.json

chore: bump @interslavic/js-utils

---

src/translations/data.json

i18n(pl): fix imperative key

---

src/components/Modals/DetailModal/DetailModal.tsx

fix(adjectives): correct table header

---

package-lock.json
package.json

Fixes superlative adverbs:
See: https://github.com/medzuslovjansky/js-utils/pull/34

chore: bump @interslavic/utils

---

src/components/ResultsCard/ResultsCard.tsx
src/components/Table/Table.tsx

| Before | After |
| --- | --- |
| ![image](https://github.com/sonic16x/interslavic/assets/1962469/a84aa3a2-c41c-4e87-9367-43b7c7ba9e38) | ![image](https://github.com/sonic16x/interslavic/assets/1962469/15967bcf-6241-4839-be9b-c1923db23980) |

fix: uško [@] rendering

---

package-lock.json
package.json

Turns out, we don't use for long time (we use sass and sass-loader).
This should unblock @bt2901 (he tried to start up the project locally)

build: remove unused node-sass

---

package-lock.json
package.json

* (Internal) Introduces short forms of adjectives (https://github.com/medzuslovjansky/js-utils/pull/64)
* Fixes compound adjectives like "podpirany od", "osnovany na" (same PR as above)
* Fixes declension of nouns like "rđa" in etymological alphabet  (https://github.com/medzuslovjansky/js-utils/pull/62)

chore: update js-utils

---

package-lock.json
package.json

Contains fixes from: https://github.com/medzuslovjansky/js-utils/pull/70
See the test report for changes in the algorithm:
https://isv-utils-allure-235.surge.sh/

chore: update @interslavic/utils

---

src/services/dictionary.ts

…with the current search algorithm.

Fix: search index

---

src/services/dictionary.ts

Add hints for irregular masculine nouns
